[package]
name = "agrf"
version = "0.3.1"
edition = "2021"
description = "Stream of int/float to unicode braille graphs"
homepage = "https://github.com/rmrfus/agrf"
repository = "https://github.com/rmrfus/agrf"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }

[profile.release]
lto = true
strip = true
